### ISSUE TITLE
Reading from PeerDirect IOMEM device fails

### ISSUE THREAD

**Issue by bartonsprings** [sbates130272/io_peer_mem#1]
- The driver build without issues
- The driver module inserted without issues
- ib_write_bw test for writing into the peer-direct PCI IOMEM device works fine
- ib_read_bw test for reading from the peer-direct PCI IOMEM device fails. Here is the error:

>  ethernet_read_keys: Couldn't read remote address
>  Unable to read to socket/rdam_cm
>  Failed to exchange data between server and clients

The command for the read tests on the system with the iomem PCI device is:
**Server Side (With the PCIe memory mapped IO device)**

```
[root@dev-h1 peerdirect]# ib_read_bw -a -F -d mlx4_0 -i 1 --mmap=/sys/bus/pci/devices/0000\:01\:00.0/resource4

* Waiting for client to connect... *
allocated mmap buffer of size 16777216 at 0x7f0bd5a2e000
---------------------------------------------------------------------------------------
                    RDMA_Read BW Test
 Dual-port       : OFF		Device         : mlx4_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Outstand reads  : 16
 rdma_cm QPs	 : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x02 QPN 0x0239 PSN 0x605dae OUT 0x10 RKey 0x8010100 VAddr 0x007f0bd622e000
 remote address: LID 0x01 QPN 0x024e PSN 0xeb1049 OUT 0x10 RKey 0xb0010100 VAddr 0x007f031134e000
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
ethernet_read_keys: Couldn't read remote address
 Unable to read to socket/rdam_cm
 Failed to exchange data between server and clients
[root@dev-h1 peerdirect]# 

**Client side to perform read from the memory mapped device on the remote system:**
[root@testmc1 nvnitro]# ib_read_bw -a -F -d mlx4_0 -i 1 1.1.1.3
---------------------------------------------------------------------------------------
                    RDMA_Read BW Test
 Dual-port       : OFF		Device         : mlx4_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Outstand reads  : 16
 rdma_cm QPs	 : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x01 QPN 0x024e PSN 0xeb1049 OUT 0x10 RKey 0xb0010100 VAddr 0x007f031134e000
 remote address: LID 0x02 QPN 0x0239 PSN 0x605dae OUT 0x10 RKey 0x8010100 VAddr 0x007f0bd622e000
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 Completion with error at client
 Failed status 11: wr_id 0 syndrom 0x89
scnt=128, ccnt=0

-----------------------------------------------------------
```
The same test without the memory mapped io device passes to host memory. Also, the same test passes for ib_write_bw to the iomem device

Any clue what could be happening?

**Comment by bartonsprings** [comment]
My observation is that on the server system with the memory mapped device the  region being locked is different from the iomem region acquired. The local iomem region acquired was **0x7f0bd5a2e000** but the infiniband read test is using the memory region **0x007f0bd622e000**. 

Here is the respective dmesg log output with kernel debug messages from io_peer_mem:

[ 3934.177658] io_peer_mem: no symbol version for ib_register_peer_memory_client
[ 3934.180070] io_peer_mem: module loaded
[ 4049.457864] CTX Address is 2901a000
[ 4049.457868] vma: 7f472901a000 1000000 50444bb 1000000
[ 4049.457870] pfn: 2fc0000000
[ 4049.457872] acquire ffff8803f677ee60
[ 4050.405993] CTX Address is 2d035000
[ 4050.405994] vma: 7f472d035000 4000 100000fb 4000
[ 4050.406000] CTX Address is 2d034000
[ 4050.406001] vma: 7f472d034000 1000 100073 1000
[ 4050.406228] CTX Address is 2d02f000
[ 4050.406228] vma: 7f472d02f000 5000 100000fb 4010
[ 4050.406231] CTX Address is 2d02e000
[ 4050.406231] vma: 7f472d02e000 1000 100073 1000
[ 4050.731802] release ffff8803f677ee60
[ 4110.048876] CTX Address is d5a2e000
[ 4110.048881] vma: 7f0bd5a2e000 1000000 50444bb 1000000
[ 4110.048884] pfn: 2fc0000000
[ 4110.048886] acquire ffff8803f677edc0
[ 4110.998690] CTX Address is d9a49000
[ 4110.998691] vma: 7f0bd9a49000 4000 100000fb 4000
[ 4110.998697] CTX Address is d9a48000
[ 4110.998698] vma: 7f0bd9a48000 1000 100073 1000
[ 4110.998968] CTX Address is d9a43000
[ 4110.998969] vma: 7f0bd9a43000 5000 100000fb 4010
[ 4110.998971] CTX Address is d9a42000
[ 4110.998972] vma: 7f0bd9a42000 1000 100073 1000
[ 4111.292546] release ffff8803f677edc0

**Comment by lsgunth** [comment]
This project is ancient and abandoned. I highly recommend you don't use it. The patch set it relies on is dead too. Use linux-p2pmem instead.

However, it vaguely sounds like your hardware is not passing p2p reads through. Your CPU may not fully support p2p transactions. We've seen that before. I suggest getting a pci switch if you really want to experiment with this stuff.

Logan

**Comment by bartonsprings** [comment]
If that is the case, why would hardware pass p2p writes but not reads? This is a Dell server T130 with Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz. Both the devices are on the same CPU complex and not on PCH etc. I will dig deeper into support for p2p for this CPU. 

Also, I did try linux-p2pmem and it did not even boot correctly. I have 10 different custom kernels I have running but linux-p2pmem does not work for some reason. I will try it again.

**Comment by bartonsprings** [comment]
Also, did you notice the message about the memory regions being locked vs the memory address acquired.   Is that working as expected or you see any issues there?

**Comment by lsgunth** [comment]
Writes are easier to do than reads. A write is a single TLP passed to a destination. A read is a TLP passed to a destination with a reply which the CPU needs to know how to route back.

I'd generally expect a Xeon cpu like that to support this but I don't really have a comprehensive list. You may also want to double check your bios to ensure things like vt-d are turned off.

Yes, the 622e address is within the region 7f0bd5a2e000 to 7f0bd6a2e000. So that seems fine.

**Comment by bartonsprings** [comment]
Thanks. I will investigate the BIOS settings. Appreciate the help. Also, I will give linux-p2pmem latest update another try.

**Comment by stephen-lb** [comment]
Hi @bartonsprings - many modern non-Xeon x86 chipsets will pass MemWr TLPs P2P but not MemRd TLPs. Annoying and confusing but true. We hit this again last week on two i5 platforms.

As @lsgunth states the best bet is to use a switch. Xeon based MoBos also fare better but I have still seen issues there too (as have you by the looks of things).

Definitely better to use linux-p2pmem. If it is not working then please register an issue for that repo with your problem.

Stephen

**Comment by bartonsprings** [comment]
Thanks Stephen. Appreciate the quick response from both of you.

I am using Xeon Server CPU as noted above. "This is a Dell server T130 with Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz. Both the devices are on the same CPU complex and not on PCH etc. I will dig deeper into support for p2p for this CPU." We will also try on a 2S server this week, time permitting.

And yes I am going to give linux-p2pmem another whirl. Last time it was unsuccessful because of boot issue in Centos 7. Should I wait for some more commits before spending a day on this journey again :)
